### ISSUE TITLE
[BUG] Images do not show on desktop under cdk8s.io features

### ISSUE THREAD

**Issue by tabern** [awslabs/cdk8s#105]
**Describe the bug**
On the [features section](https://cdk8s.io/#Features) of the website, images show next to the feature descriptions on mobile, but not on the desktop.

**To Reproduce**
Open https://cdk8s.io/#Features in a desktop browser.

**Expected behavior**
Images render. Images need to be updated, also.

**Additional context**
Could be a Hugo problem. Need to look at HTML/CSS source code.

**Comment by deepgorthi** [comment]
Hi @tabern, I am looking to contribute to this project. I came across your Issue but I do not see a problem in the website similar to what you mentioned. Is this issue closed/resolved?

**Comment by eladb** [comment]
I think this is no longer an issue.
