### ISSUE TITLE
Java support

### ISSUE THREAD

**Issue by eladb** [awslabs/cdk8s#117]
Tracking issue for Java support in cdk8s. Please +1 this issue to let us know you care (no need to comment).

**Comment by rask** [comment]
I presume with Java support Kotlin would be covered as well. Though Kotlin/JS might work already?

**Comment by GregoryHlavac** [comment]
Though, specific kotlin support could be nicer with how the DSL syntax in it can work.

**Comment by campionfellin** [comment]
Java support is now implemented.

Blog post announcing it: https://aws.amazon.com/blogs/containers/announcing-java-support-for-cdk8s/

---

Kotlin support can be tracked here: https://github.com/aws/jsii/issues/1541

Closing this one.
