### ISSUE TITLE
[cdk8s] Escape hatches

### ISSUE THREAD

**Issue by eladb** [awslabs/cdk8s#144]
Similarly to how [escape hatches] work in the AWS CDK.

[escape hatches]: https://docs.aws.amazon.com/cdk/latest/guide/cfn_layer.html

**Comment by campionfellin** [comment]
Assigned myself to start working on this!

**Comment by eladb** [comment]
@campionfellin Great!

Let’s try to do a mini-RFC for this to finalize the API.

Basically just submit your PR with only the README entry (“work backwards from the readme”).

**Comment by iliapolo** [comment]
Once this is implemented, we should offer a solution to [this bug](https://github.com/awslabs/cdk8s/issues/140) based on it.
