### ISSUE TITLE
[BUG] Bad import of cert-manager CRDs

### ISSUE THREAD

**Issue by mbonig** [awslabs/cdk8s#147]
**Describe the bug**
When importing the CRDs for cert-manager (<1.15) from here: https://github.com/jetstack/cert-manager/releases/download/v0.15.0/cert-manager-legacy.yaml the resulting generated code is missing some definitions.

**To Reproduce**
Download the above mentioned .yaml and try to import. A resulting class is generated:
```
export class Issuer extends ApiObject {
  /**
   * Defines a "Issuer" API object
   * @param scope the scope in which to define this object
   * @param name a scope-local name for the object
   * @param options configuration options
   */
  public constructor(scope: Construct, name: string, options: IssuerOptions = {}) {
    super(scope, name, {
      ...options,
      kind: 'Issuer',
      apiVersion: 'cert-manager.io/v1alpha2',
    });
  }
}
```

However, the IssuerOptions is not generated.

**Expected behavior**
I expected the IssuerOptions to be generated.

**Comment by campionfellin** [comment]
Using latest commit, I'm getting:

```
export class Issuer extends ApiObject {
  /**
   * Defines a "Issuer" API object
   * @param scope the scope in which to define this object
   * @param name a scope-local name for the object
   * @param options configuration options
   */
  public constructor(scope: Construct, name: string, options: any = {}) {
    super(scope, name, {
      ...options,
      kind: 'Issuer',
      apiVersion: 'cert-manager.io/v1alpha2',
    });
  }
}
```

and it also works without downloading locally ( I noticed something about this in the slack channel).

https://github.com/awslabs/cdk8s/commit/1ed88ca32c998b590093fd0090ecbf9a6662043e fixes the redirect

https://github.com/awslabs/cdk8s/commit/b8115cb809b2b33be73a98f99b1cefa4de152654 leads to `options: any = {}`

That `cert-manager-legacy` definition is pretty long, what do you expect for the options?

---

I'll open a PR to bump the version so you can at least get those bug fixes!

**Comment by eladb** [comment]
Should be resolved in the latest release
