### ISSUE TITLE
[BUG] cdk8s init throws error on missing prerequisites

### ISSUE THREAD

**Issue by ankitmahapatra22** [awslabs/cdk8s#163]
**Describe the bug**
cdk8s init typescript-app throws file already exists error.
OS : Windows 8.1
Node version : 10.11.0

**To Reproduce**
cdk8s init typescript-app

**Expected behavior**
New project should have been created.

**Additional context**
Getting started using https://github.com/awslabs/cdk8s/blob/master/docs/getting-started/typescript.md

![cdk8s init issue](https://user-images.githubusercontent.com/3295308/81981766-61c2e700-964e-11ea-9678-cded5141d7ac.PNG)

**Comment by stanleynguyen** [comment]
It looks like you were trying to init `hello/` and the folder already existed (which explains the OS error)

**Comment by jmmars** [comment]
No.

> (base) ➜  cdk8s git:(master) ✗ cd hello
> (base) ➜  hello git:(master) ✗ cdk8s init python-app
> Initializing a project from the python-app template
> cdk8s init TYPE
> 
> Create a new cdk8s project from a template.
> 
> Positionals:
>   TYPE  Project type                                                                                                [required] [choices: "python-app", "typescript-app"]
> 
> Options:
>   --version        Show version number                                                                                                                         [boolean]
>   --help           Show help                                                                                                                                   [boolean]
>   --dist           Install dependencies from a "dist" directory (for development)                                                                               [string]
>   --cdk8s-version  The cdk8s version to use when creating the new project                                                                   [string] [default: "0.21.0"]
> 
> TypeError: Cannot read property 'mkdir' of undefined
>     at Object.sscaff (/Users/xyz/.npm-global/lib/node_modules/cdk8s-cli/node_modules/sscaff/lib/sscaff.js:18:25)
>     at Object.handler (/Users/xyz/.npm-global/lib/node_modules/cdk8s-cli/bin/cmds/init.js:29:24)
>     at <anonymous>
>     at process._tickCallback (internal/process/next_tick.js:188:7)
>     at Function.Module.runMain (module.js:686:11)
>     at startup (bootstrap_node.js:187:16)
>     at bootstrap_node.js:608:3

**Comment by campionfellin** [comment]
Hey, could you try with Node 12?

**Comment by jmmars** [comment]
heh ... hold on..
```

(base) ➜  hello git:(master) ✗ node --version
v12.16.3
(base) ➜  hello git:(master) ✗ cdk8s init python-app
Initializing a project from the python-app template
Unable to find "pipenv". Install from https://pipenv.kennethreitz.org

```

**Comment by jmmars** [comment]
So, the solution (update the docs maybe unless I missed these two things in there... ) is to use some version of node >= 12.x (I was using v8.9.4) _and_ to install pipenv (`brew install pipenv`). So, I take it back, guess my node was crusty.

**Comment by eladb** [comment]
> So, the solution (update the docs maybe unless I missed these two things in there... ) is to use some version of node >= 12.x (I was using v8.9.4) _and_ to install pipenv (`brew install pipenv`). So, I take it back, guess my node was crusty. 
> 
> 

can you submit a PR for doc update?

**Comment by ankitmahapatra22** [comment]
Thank you, upgrading the Node version to LTS 12.16.3 helped create the typescript-app templated project successfully. 
Next I went on to init using python-app template. Similar to @jmmars , I encountered the pipenv installation message.
Went on to install pipenv - ```pip install --user pipenv```
Followed it up with 
```cdk8s init python-app```
in a new folder name hello_python
Received the error as seen in below screenshot 
![cdk8s_pytho_app_1](https://user-images.githubusercontent.com/3295308/82048656-a728f800-96d2-11ea-90b2-505c0b25b937.PNG)

Read somewhere that which keyword is not supported in Windows.
Switched to using git bash instead.

It failed at the import part
```cdk8s import k8s -l python```
![cdk8s_python_app_2](https://user-images.githubusercontent.com/3295308/82049485-03d8e280-96d4-11ea-87a3-ca2284f266da.PNG)

Realized it maybe a permission issue , so ran git bash in Administrator mode and now it seems jsii bin folder is missing within cdk8s-cli node_modules folder
![cdk8s_python_app_3](https://user-images.githubusercontent.com/3295308/82051240-21f41200-96d7-11ea-8e2c-afd423d32a7e.PNG)

**Comment by jmmars** [comment]
> can you submit a PR for doc update?
I'll  see if I can patch this getting-started/python.md this weekend after looking over your contrib guide. Basically, it just needs to be clearer on prereqs. 

Looking forward: At some point, for some systems might be able to do a more programmatic check to make sure base reqs will enable an easy install.

**Comment by eladb** [comment]
Is this still relevant? Closing for now.
