### ISSUE TITLE
Golang alpha - something to test/play with

### ISSUE THREAD

**Issue by JCzz** [awslabs/cdk8s#167]
This is so cool and so the right direction for K8s configuration - thanks!

Any way we can test/play and help with Go support?

**Comment by rafaribe** [comment]
https://github.com/awslabs/cdk8s/issues/119
Upvote this if you care about go !

**Comment by JCzz** [comment]
Thanks already did ;-) But this will not be created in a day, so maybe something is on the way we can play with - or maybe just get started with client-go.

**Comment by eladb** [comment]
Closing as duplicate
