### ISSUE TITLE
Add a lib folder and some extra constructs to generated project

### ISSUE THREAD

**Issue by ankitmahapatra22** [awslabs/cdk8s#189]
### Description of the feature or enhancement:

I found the new WebService construct documented in https://github.com/awslabs/cdk8s/blob/master/docs/getting-started/typescript.md very useful and I think it should be created by default in the generated project within the lib folder. 
Custom constructs for databases like Redis, Postgres can be added to the lib folder.

### Use Case:
Higher abstraction. Reduced copy paste efforts and more API kind experience for the developer.
For bulk of the cases , default ports would be used anyways.
If the user wants any more customization , they can either modify the construct or extend it to add features.

### Proposed Solution:
![cdk8s_enhancement](https://user-images.githubusercontent.com/3295308/82697762-27c59680-9c87-11ea-85b4-eac8c61b7182.PNG)

### Other:
Update the documentation showcasing how to use shipped extended constructs.

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by eladb** [comment]
We prefer not to bloat our project templates. The recommended way to vend abstractions in the cdk8s is to publish construct libraries such as [cdk8s-debore](https://github.com/toricls/cdk8s-debore), [cdk8s-redis](https://github.com/toricls/cdk8s-redis) and [more](https://github.com/dungahk/awesome-cdk8s).
