### ISSUE TITLE
add ability to add spec to Deployment after object creation

### ISSUE THREAD

**Issue by FlorianLudwig** [awslabs/cdk8s#193]
### Description of the feature or enhancement:

After creating a `k8s.Deployment` it seems not possible to add a `k8s.DeploymentSpec`.

### Use Case:

Making code easier to read and more flexible. 

"You can express rich interactions with methods and properties" from [programmatically defined Helm chart](https://github.com/awslabs/cdk8s/blob/master/docs/getting-started/python.md#constructs).

### Proposed Solution:

```python

>>> d = k8s.Deployment(c, 'deployment')
>>> d.spec = k8s.DeploymentSpec(...)
```

---

This is a :rocket: Feature Request

**Comment by eladb** [comment]
Duplicate #160
