### ISSUE TITLE
cdk8s installation issue

### ISSUE THREAD

**Issue by sumit180591** [awslabs/cdk8s#214]
While installing cdk8s on centos 7 I encountered with following error:

```
Bash completion has been installed to:
/home/linuxbrew/.linuxbrew/etc/bash_completion.d
==> Summary
/home/linuxbrew/.linuxbrew/Cellar/node/14.3.0: 4,658 files, 69.2MB
==> Installing cdk8s
Error: An exception occurred within a child process:
RuntimeError: npm failed to pack /tmp/cdk8s-20200526-77213-i9fl4r/package
```

And while installing with npm I got this error:

```
[root@kubemaster1 ~]# npm install -g cdk8s-cli
/usr/lib
└── (empty)
npm ERR! Linux 3.10.0-1062.4.1.el7.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "cdk8s-cli"
npm ERR! node v6.17.1
npm ERR! npm v3.10.10
npm ERR! path /usr/lib/node_modules/.staging/@babel/runtime-77045e9f
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename '/usr/lib/node_modules/.staging/@babel/runtime-77045e9f' -> '/usr/lib/node_modules/cdk8s-cli/node_modules/cdk8s/node_modules/@babel/runtime'
npm ERR! enoent ENOENT: no such file or directory, rename '/usr/lib/node_modules/.staging/@babel/runtime-77045e9f' -> '/usr/lib/node_modules/cdk8s-cli/node_modules/cdk8s/node_modules/@babel/runtime'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent
npm ERR! Please include the following file with any support request:
npm ERR! /root/npm-debug.log
npm ERR! code 1
```

Reference link: https://github.com/awslabs/cdk8s/blob/master/docs/getting-started/python.md

**Comment by eladb** [comment]
Can you please upgrade to node >= 13.0?

**Comment by sumit180591** [comment]
> Can you please upgrade to node >= 13.0?

Thanks for quick response!!!

I have upgrade the node and try the following command:-
cdk8s]$ sudo cdk8s init python-app
Initializing a project from the python-app template
which: no pipenv in (/sbin:/bin:/usr/sbin:/usr/bin)
Unable to find "pipenv". Install from https://pipenv.kennethreitz.org

Additionally FYI I have already install pipenv with following command :-
brew install pipenv

**Comment by sumit180591** [comment]
Thanks for a quick reply!!!!

Its worked for me...Now I am getting the following issue 
Please find the attachment
![cdk8s](https://user-images.githubusercontent.com/65972884/83035391-04b82f80-a057-11ea-9c66-3ccd047eaf59.PNG)

**Comment by eladb** [comment]
Dup #163
