### ISSUE TITLE
Options type not generated for Elasticsearch CRD

### ISSUE THREAD

**Issue by erdody** [awslabs/cdk8s#219]
### Description of the bug:

After running the import on [elasticsearch CRDs](https://github.com/elastic/cloud-on-k8s/blob/master/config/crds/all-crds.yaml#L458), I don't see a type for the options field. This is all I get:

```
export class Elasticsearch extends ApiObject {
  /**
   * Defines a "Elasticsearch" API object
   * @param scope the scope in which to define this object
   * @param name a scope-local name for the object
   * @param options configuration options
   */
  public constructor(scope: Construct, name: string, options: any = {}) {
    super(scope, name, {
      ...options,
      kind: 'Elasticsearch',
      apiVersion: 'elasticsearch.k8s.elastic.co/v1',
    });
  }
}
```

### Reproduction Steps:

```
cdk8s import  https://raw.githubusercontent.com/elastic/cloud-on-k8s/master/config/crds/all-crds.yaml
```

### Error Log:

No errors in the logs. Import succeeds, but it doesn't generate the options type.

### Environment:

  - cdk8s 0.24.0
  - MacOS 10.14.6

--- 

This is :bug: Bug Report

**Comment by abtalerico** [comment]
I have been seeing the same issue with these CRDs. They both contain OpenAPIV3 schemas.
[Flagger](https://raw.githubusercontent.com/weaveworks/flagger/master/artifacts/flagger/crd.yaml)
[Argo CD Application](https://raw.githubusercontent.com/argoproj/argo-cd/master/manifests/crds/application-crd.yaml)

**Comment by eladb** [comment]
Thanks, looking.
