### ISSUE TITLE
Real world examples

### ISSUE THREAD

**Issue by tabern** [awslabs/cdk8s#22]
- [ ] pure K8s app example
- [ ] stateless AWS app example
- [ ] stateful AWS app example

add to [/examples](/awslabs/cdk8s/tree/master/examples)

**Comment by campionfellin** [comment]
@tabern I'd offer this repository as a real world example: [`campionfellin/cdk8s-cicd-example`](https://github.com/campionfellin/cdk8s-cicd-example)

Is there somewhere you suggest to put external examples that do not belong in`/examples`?
