### ISSUE TITLE
Setting the namespace seems to be broken for Python 

### ISSUE THREAD

**Issue by nimakaviani** [awslabs/cdk8s#225]
### Description of the bug:

I am using ckd8s v 0.24.0 and I have tried to set the namespace when deploying the `hello world` example both for Python and Typescript.

I noticed PR https://github.com/awslabs/cdk8s/pull/68 allows for setting the namespace by passing it as a chart option.

For the [Typescript version of hello world](https://github.com/awslabs/cdk8s/tree/85cf6313c20771b718c19ee6085afc23cd787311/examples/typescript/hello), I can use the the option like the following, and the generated output has the namespace set on the resources:

```
export class HelloKube extends Chart {
  constructor(scope: Construct, id: string, ns: string) {
    super(scope, id, {namespace: ns});
  }
}
```

for the [Python version of hello world](https://github.com/awslabs/cdk8s/tree/9cab302939c3d8ce3104e30d2bd1ad22b87bcbf8/examples/python/hello) however, I have the very similar snippet below:

```
class MyChart(Chart):
    def __init__(self, scope: Construct, ns: str, nsp: str):
        super().__init__(scope, ns, ChartOptions( namespace=nsp ))
```

but running `cdk8s synth` gives me the following error:

```
Traceback (most recent call last):
  File "./main.py", line 32, in <module>
    MyChart(app, "hello-python", "default")
  File "/Users/nkaviani/.local/share/virtualenvs/cdk8s-sample-7s8UNO4D/lib/python3.7/site-packages/jsii/_runtime.py", line 66, in __call__
    inst = super().__call__(*args, **kwargs)
  File "./main.py", line 9, in __init__
    super().__init__(scope, ns, ChartOptions( namespace=nsp ))
TypeError: __init__() takes 3 positional arguments but 4 were given
Error: command "pipenv run ./main.py " at /private/tmp/test2/cdk8s-sample returned a non-zero exit code 1
    at ChildProcess.<anonymous> (/usr/local/Cellar/cdk8s/0.24.0/libexec/lib/node_modules/cdk8s-cli/lib/util.js:23:27)
    at Object.onceWrapper (events.js:422:26)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
```

Am I missing something or is this a regression?

thanks!

--- 

This is :bug: Bug Report

**Comment by eladb** [comment]
No need to use `ChartOptions`, this should work:

```py
from constructs import Construct
from cdk8s import App, Chart, ApiObject


class MyChart(Chart):
    def __init__(self, scope: Construct, ns: str):
        super().__init__(scope, ns, namespace="foo")

        ApiObject(self, 'foo', api_version='v1', kind='Foo')



app = App()
MyChart(app, "py225")

app.synth()
```
