### ISSUE TITLE
Java Issue Importing Jenkins CRD

### ISSUE THREAD

**Issue by campionfellin** [awslabs/cdk8s#234]
### Description of the bug:

I'm trying to import this CRD: https://raw.githubusercontent.com/jenkinsci/kubernetes-operator/master/deploy/crds/jenkins.io_jenkins_crd.yaml

But the Java package name ends up as `jenkins.io/jenkins` which is invalid.

### Reproduction Steps:

`cdk8s import -l java https://raw.githubusercontent.com/jenkinsci/kubernetes-operator/master/deploy/crds/jenkins.io_jenkins_crd.yaml`

### Error Log:

No error. This is where we should look at fixing:

https://github.com/awslabs/cdk8s/blob/b1fa11d6062dc5008e4e263cf556695a64ae88ad/packages/cdk8s-cli/lib/import/crd.ts#L73-L75

### Environment:

  - **Framework Version**: latest (`0.25.0`)
  - **OS**: macOS Catalina 10.15.3

### Other:

* Either change module name conventions in the code linked above
* Or handle this per-language

--- 

This is :bug: Bug Report

**Comment by eladb** [comment]
I think the fix should be in the java import code path. `moduleName` is "agnostic" and each language should mangle it based on it's constraints.
