### ISSUE TITLE
Omit duplicate components when rendering object names

### ISSUE THREAD

**Issue by eladb** [awslabs/cdk8s#236]
### Description of the feature or enhancement:

As sugar, we should omit adjacent duplicate components when rendering object names.

Instead of:

    redrive-redrive-app-configmap-e2d51b95

We should render:

    redrive-app-configmap-e2d51b95

### Use Case:

Shorten the names.

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by campionfellin** [comment]
I'll take this on next.

**Comment by eladb** [comment]
Cool. Perhaps needless to say, but the hash component should not change.

**Comment by campionfellin** [comment]
Yeah, mostly done here. What do you want in these two cases?

```
1. toDnsName('hello-hello-foo-world') --> case where it's specifically set to have the dupes
2. toDnsName('hello-foo/foo') --> case where it's somewhat accidental
```

Easy case is `toDnsName('hello/hello/foo/world')` and I think for 2. we could go with `hello-foo`, but seems like 1. is pretty intentionally duplicate. Does that make sense or do we want to remove from all?

**Comment by eladb** [comment]
> 
> 1. toDnsName('hello-hello-foo-world') --> case where it's specifically set to have the dupes
> 

Leave as is. Agreed.

> 2. toDnsName('hello-foo/foo') --> case where it's somewhat accidental 

Mmm... let’s leave as is as well.
