### ISSUE TITLE
Create multi-line data for Secret object

### ISSUE THREAD

**Issue by mjwilkerson-strateos** [awslabs/cdk8s#277]
How can I enter multi-line data in the cdk8 Secret object?

```ts
new Secret(this, 'secret', {
      metadata: {
        name: 'rabbitmq-load-definition'
      },
      data: ??
    });
```

**Comment by mjwilkerson-strateos** [comment]
Actually, I think I need stringData, but it' still the same issue

**Comment by mjwilkerson-strateos** [comment]
I'm aiming for a manifest similar to:

stringData:
  load_definition.json: |-
    {
      "vhosts": [
        {
          "name": "/"
        }
      ],

**Comment by iliapolo** [comment]
Should just the standard way you specify multiline strings in typescript. 

Have you tried:

```typescript
new Secret(this, 'secret', {
      metadata: {
        name: 'rabbitmq-load-definition'
      },
      stringData: {
        'key': `this is a
multi-line string` // notice the backtick (`)
      }
    });
```

Also, if you just need a serialized json as the value you can do:

```typescript
new Secret(this, 'secret', {
      metadata: {
        name: 'rabbitmq-load-definition'
      },
      stringData: {
        'key': JSON.stringify(object) // or maybe fs.readFileSync() if you are reading a file.
      }
    });
```

**Comment by eladb** [comment]
Another common idiom would be:

```ts
new Secret(this, 'secret', {
      stringData: [
        'line1',
        'line2',
        'line3',
      ].join('\n')
}
```

**Comment by mjwilkerson-strateos** [comment]
Thank you, much appreciated, I'm new to both typescript and cdk8s. I'm going to try this again today and I'll update this issue.

**Comment by mjwilkerson-strateos** [comment]
Thank you for the solutions, all of them are working.
