### ISSUE TITLE
Import an existing k8s yaml file to generate the code

### ISSUE THREAD

**Issue by cassador** [awslabs/cdk8s#278]
Hello, i am aware that you have the Include option for attaching and maintaining existing templates that way, but was hoping for a little more :) 

### Description of the feature or enhancement:

The feature would be able to import an already existing kubernetes yaml templates to create a code as would developer normally write. Meaning the cdk8s synth is taking the code and makes kubernetes yaml file from it, but this would be doing it revertly.

It could be called cdk8s resynth ( as reverse synth)

### Use Case:

Imagine you have already a set of templates running in production for many applications. Now the cdk8s is great and better then using notepad++ but rewrite hundreds of templates could take an effort for which the company might not be willing to go for. But with this feature it could be a matter of few minutes.

This is a :rocket: Feature Request

**Comment by campionfellin** [comment]
Hey @cassador would this be the same as the proposed `cdk8s dasm`, from https://github.com/awslabs/cdk8s/issues/141?

**Comment by cassador** [comment]
Hey @campionfellin  yes it is indeed the same, i might have missed that, when i was checking if someone didn't mention already that feature. Then we might close this as it is duplicate :)

**Comment by campionfellin** [comment]
Awesome, sounds good :)
