### ISSUE TITLE
CDK8S Synth to multiple files instead of single one

### ISSUE THREAD

**Issue by cassador** [awslabs/cdk8s#279]
### Description of the feature or enhancement:

Have an ability to synthetize not only to single yaml file but to multiple ones based on the different types. 
For example if there would be deployment and service then the output would be app-deployment.yaml and app-service.yaml

### Use Case:

With Jenkins CI/CD automatization and usage of multiple configmaps and secrets people might not want to run all stuff to be deployed but have an better control over it, as just some small changes might be required like increased image version, so it doesn't make a sense to run kubectl command cross N files when only for one would be sufficient.  

Also additional use case is when writing an helm charts. The helm chart usually use multiple k8s templates instead of single one large ,when if error occur at start it stops the remaining of the yaml file to be run, which can cause an issue when the change which fails is configmap after deployment section, while the application would be expecting to have the configmap sooner, eventually the configmap can pass with changed values while application will crash and while performing rollback to last stable version, this might not get loaded correctly.

### Other:

Current workaround is that i manually split the files to multiple ones.

This is a :rocket: Feature Request

**Comment by iliapolo** [comment]
Hi @cassador 

Currently, every `Chart` with produce its own file, using the id you provide it. So if you want to produce multiple manifest, you can place your resources in different charts. 

Is that sufficient? Or do you think finer granularity for separate files is needed?

**Comment by cassador** [comment]
Hi @iliapolo .
So if i understood it correctly within the single .ts file i can have multiple charts which will give that result?

I will try that later tomorrow if i will have time for that and i will let you know about an opinion about it.

It will heavily depend on how the code in .ts file will look like, if that would not be too much chaotic.

**Comment by iliapolo** [comment]
@cassador the .ts files can be structured any way you like. They don't impact the resulting manifest files structure.

You can create multiple charts and just pass them around between multiple ts source files, all resources that belong to a specific chart will be synthesized to the same manifest file.

**Comment by cassador** [comment]
@iliapolo  thank you, i did try it and it's behaving as expected. It will just require from my end a little more practical experience how to write it more human readable friendly :).
