### ISSUE TITLE
Documentation on using the CDK8s CLI

### ISSUE THREAD

**Issue by tabern** [awslabs/cdk8s#28]
- [ ] `cdk8s init`
- [ ] `cdk8s generate`
- [ ] changing the default version of the K8s API
- [ ] K8s custom resource definitions

**Comment by campionfellin** [comment]
`changing the default version of the K8s API` could be documented like this:

---

By default, the command `cdk8s import k8s` will use the latest stable version of k8s objects.

For example, when using k8s 1.17,  if you want to use `DeploymentSpec`, you would be importing it from [Deployment v1](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.17/#deploymentspec-v1-apps) by default. 

In the default `v1`, the `revisionHistoryLimit`, which is the number of old ReplicaSets to retain, is set to 10 by default. You would have to explicitly set this to a higher number if you want to retain more.

Let's say that you want the behavior of [extensions/v1beta1](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.17/#deploymentspec-v1beta1-extensions), which defaults to retaining _all_ old ReplicaSets.

To do this, you could add the `--include` flag to your `cdk8s import`. Here is how that would look:

```code
cdk8s import k8s --language typescript --include io.k8s.api.extensions.v1beta1.Deployment
```

Here we are explicitly choosing to use the [Deployment extensions/v1beta1](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.17/#deployment-v1beta1-extensions) version, which includes the new default behavior that we want from `DeploymentSpec`
