### ISSUE TITLE
cdk8s synth - "ModuleNotFoundError: No module named 'constructs'

### ISSUE THREAD

**Issue by shivaramani** [awslabs/cdk8s#289]
### Description of the bug:

When we create a new folder, "cdk8s init python-app" (and if we add our code to create chart/webservice)  “cdk8s synth” works.. it creates dist/output.yaml 

Whereas if we try to “cdk8s synth” on an existing folder (where we have main.py/webservice.py and cdk8s.yaml) we get imports error (ex: this example https://github.com/awslabs/cdk8s/tree/master/examples/python/web-service)

“cdk8s synth” on an existing folder (ex: download the above contents into a folder) we get imports error, if cdk8s synth would work only on a folder only when initialized

**Getting ModuleNotFoundError: No module named 'constructs'**

Detailed error:

```console
$ cdk8s synth
Traceback (most recent call last):
  File "./main.py", line 2, in <module>
    from constructs import Construct
ModuleNotFoundError: No module named 'constructs'
Error: command "pipenv run ./main.py " at /Users/REDACTED/Documents/Code/AWS/cdk8s/cdk8s/examples/python/web-service returned a non-zero exit code 1
    at ChildProcess.child.once.code (/Users/REDACTED/.nvm/versions/node/v10.15.3/lib/node_modules/cdk8s-cli/lib/util.js:24:27)
    at Object.onceWrapper (events.js:277:13)
    at ChildProcess.emit (events.js:189:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
```

### Reproduction Steps:

```bash
$ git clone https://github.com/awslabs/cdk8s
$ cd cdk8s/examples/python/web-service
$ pipenv install
$ cdk8s import --language python
$ cdk8s synth
```

### Error Log:
```console
Traceback (most recent call last):
  File "./main.py", line 2, in <module>
    from constructs import Construct
ModuleNotFoundError: No module named 'constructs'
Error: command "pipenv run ./main.py " at /Users/REDACTED/Documents/Code/AWS/cdk8s/cdk8s/examples/python/web-service returned a non-zero exit code 1
    at ChildProcess.child.once.code (/Users/REDACTED/.nvm/versions/node/v10.15.3/lib/node_modules/cdk8s-cli/lib/util.js:24:27)
    at Object.onceWrapper (events.js:277:13)
    at ChildProcess.emit (events.js:189:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
```

### Environment:

  - **Framework Version**: 
cdk8s --version - 0.27.0
python --version - Python 3.7.6
pipenv, version 2018.11.26

  - **OS**: MAC

### Other:

--- 

This is :bug: Bug Report

**Comment by igorborgest** [comment]
The regular flow should be something like:

```shell
# install pipenv
pip install pipenv

# initialise virtual environment (inside the project's directory)
pipenv install

# run what you want from inside the virtual environment
pipenv run cdk8s synth
```

But seems that these examples are missing some required dependencies (fixed in the PR above.)

**Comment by shivaramani** [comment]
Thank you so much.
Tried another example with the fix.

Added the below packages (similar to your fix - [commit](https://github.com/awslabs/cdk8s/pull/290/files))

[packages]
constructs = "==2.0.2"
cdk8s = "~=0.26.0"

Ran these:
$ pip install pipenv
$ pipenv install
$ cdk8s synth
dist/cdk8s.k8s.yaml
