### ISSUE TITLE
[cdk8s-plus] Service in cdk8s-plus cannot extract the nodePort property to a YAML

### ISSUE THREAD

**Issue by y-taka-23** [awslabs/cdk8s#296]
### Description of the bug:

You can pass the `nodePort` property to `ServicePortOptions` in cdk8s-plus, but it looks to be discarded during extraction by `_toKube()`.

### Reproduction Steps:

1. `mkdir repro && cd repro`
1. `cdk8s init typescript-app`
1. `npm install cdk8s-plus`
1. Edit `main.ts` as follows
1. `npm run compile && cdk8s synth`

```typescript
import { Construct } from 'constructs';
import { App, Chart } from 'cdk8s';
import { Service } from 'cdk8s-plus';

export class MyChart extends Chart {
  constructor(scope: Construct, name: string) {
    super(scope, name);

    const service = new Service(this, 'mysvc');
    service.spec.serve(80, { nodePort: 30080 });
  }
}

const app = new App();
new MyChart(app, 'repro');
app.synth();
```

### Environment:

  - **Framework Version**: cdk8s-plus@0.27.0

### Other:

If you don't mind, I'm willing to pick the issue up.

--- 

This is :bug: Bug Report

**Comment by iliapolo** [comment]
@y-taka-23 

> If you don't mind, I'm willing to pick the issue up.

Yes - that would be awesome! 

I'm here to help :)
