### ISSUE TITLE
[cdk8s] ts: Enforce ServiceSpec types 

### ISSUE THREAD

**Issue by jwnx** [awslabs/cdk8s#314]
### Description of the feature or enhancement:
As of now, most of `ServiceSpec` types (and others, actually) are string typed. Some props, though, could be easily type enforced in order to avoid errors. `externalTrafficPolicy`, for example. 

### Use Case:
We don't want failed deploys due to mistyping. Plus, being aware of the actual configuration options saves us a lot of time when coding (:

### Proposed Solution:
Scan kubernetes documentation looking for typing restrictions and implement them in cdk8s.

### Other:

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by iliapolo** [comment]
@jwnx The types of the generated properties are derived from the json schema. 

The `externalTrafficPolicy` property is unfortunately types as a string, not an enum:

https://github.com/instrumenta/kubernetes-json-schema/blob/master/v1.15.0/_definitions.json#L11058-L11060

```json
"externalTrafficPolicy": {
  "description": "externalTrafficPolicy denotes if this Service desires to route external traffic to node-local or cluster-wide endpoints. \"Local\" preserves the client source IP and avoids a second hop for LoadBalancer and Nodeport type services, but risks potentially imbalanced traffic spreading. \"Cluster\" obscures the client source IP and may cause a second hop to another node, but should have good overall load-spreading.",
  "type": "string"
```

I'm not sure scanning the documentation itself is a sustainable method of enforcing types. 

This is exactly the type of stuff that can be solved in [cdk8s-plus](https://github.com/awslabs/cdk8s/blob/master/packages/cdk8s-plus/src/service.ts).

Closing in favor of https://github.com/awslabs/cdk8s/issues/301
