### ISSUE TITLE
Yaml files generated with synth do not quote strings which can be interpreted as native non-string types

### ISSUE THREAD

**Issue by gabe-l-hart** [awslabs/cdk8s#325]
### Description of the bug:

When `app.synth()` generates `yaml` files, values which are strings in memory are rendered without quotes in the `yaml` files. This can cause problems for string values such as `"true"`, `"yes"`, and `"2020-01-01"`. These strings, when rendered without quotes, will be read as native data types by `yaml` parsers such as `PyYaml` (`true` and `yes` become python `bool`, while `2020-01-01` becomes `datetime.datetime`).

### Reproduction Steps:

```py
import cdk8s
import yaml

# Create the chart with the unquoted values
app = cdk8s.App()
chart = cdk8s.Chart(app, "test")
cdk8s.ApiObject(chart, "foo", api_version="v1", kind="Foo", metadata={"annotations": {"bar": "2020-01-01", "baz": "on"}})
app.synth()

# Reread the generated file with pyyaml
with open('dist/test.k8s.yaml', 'r') as f:
    objects = list(yaml.safe_load_all(f))

# Print out some info about the re-read types
for key in ["bar", "baz"]:
    print(f"--> {key}")
    print(objects[0]["metadata"]["annotations"][key])
    print(type(objects[0]["metadata"]["annotations"][key]))
```

**Output**
```
--> bar
2020-01-01
<class 'datetime.date'>
--> baz
True
<class 'bool'>
```

**Rendered yaml**
```yaml
apiVersion: v1
kind: Foo
metadata:
  annotations:
    bar: 2020-01-01
    baz: on
  name: test-foo-657aa33b
```

### Error Log:

There are no immediate errors. See the rendered yaml and script output above.

### Environment:

  - **Framework Version**:

```
pip freeze | grep cdk8s
cdk8s==0.27.0
```

  - **OS**: Mac OS, `conda` w/ python 3.6

### Other:

--- 

This is :bug: Bug Report

**Comment by gabe-l-hart** [comment]
I suspect the issue may be in the `yaml` renderer [here](https://github.com/awslabs/cdk8s/blob/master/packages/cdk8s/src/app.ts#L59)

**Comment by gabe-l-hart** [comment]
It's possible that bumping the [version of `yaml`](https://github.com/awslabs/cdk8s/blob/master/packages/cdk8s/package.json#L64) to the latest may help here. There seem to be a lot of differences in versions in that library relative to `1.7.2`: https://github.com/eemeli/yaml

**Comment by gabe-l-hart** [comment]
I was able to reproduce this with just `1.7.2` of the `yaml` package:

**test.yaml**
```yaml
foo: "on"
bar: "2020-01-01"
```

```js
yaml = require('yaml');
fs = require('fs');

const content = fs.readFileSync('test.yaml', 'utf8')
const parsed = yaml.parse(content)
console.log(parsed)
const serialized = yaml.stringify(parsed)
console.log(serialized)
```

**Comment by gabe-l-hart** [comment]
This issue looks relevant: https://github.com/eemeli/yaml/issues/198

**Comment by gabe-l-hart** [comment]
Based on that issue, it looks like this can be solved on the version `2.0.0-0` version of the library by adding lines like the following:

```js
yaml.scalarOptions.str.defaultType = 'QUOTE_DOUBLE'
yaml.scalarOptions.str.defaultKeyType = 'PLAIN'
```

**Comment by CAR6807** [comment]
TypeScript - `cdk8s: 0.27.0 (also seen in 0.28.0)`

Also running into this as well when rendering YAML
This becomes an issue in pre-1.17 Kubernetes as annotations silently fail if it is a num or bool value
https://github.com/kubernetes/kubernetes/issues/88564

TypeScript snippet
```
       annotations: {
            "annotation/number" : "12345",
            "annotation/date": "2020-10-10",
            "annotation/boolean": "true",
            "annotation/string": "should be in quotes"
        },
```
Rendered YAML

```
  annotations:
    annotation/number: "12345"
    annotation/date: 2020-10-10
    annotation/boolean: "true"
    annotation/string: should be in quotes
```

**Comment by eladb** [comment]
> Based on that issue, it looks like this can be solved on the version `2.0.0-0` version of the library by adding lines like the following:
> 
> ```js
> yaml.scalarOptions.str.defaultType = 'QUOTE_DOUBLE'
> yaml.scalarOptions.str.defaultKeyType = 'PLAIN'
> ```
> 
> Using those lines, I was able to get the serialized output to contain the quotes:
> 
> ```js
> yaml = require('yaml');
> fs = require('fs');
> 
> yaml.scalarOptions.str.defaultType = 'QUOTE_DOUBLE'
> yaml.scalarOptions.str.defaultKeyType = 'PLAIN'
> 
> const content = fs.readFileSync('test.yaml', 'utf8')
> const parsed = yaml.parse(content)
> console.log(parsed)
> const serialized = yaml.stringify(parsed)
> console.log(serialized)
> ```

@gabe-l-hart would you like to submit a PR to upgrade `yaml`?

**Comment by gabe-l-hart** [comment]
@eladb Yes, will do!

**Comment by gabe-l-hart** [comment]
@eladb I've set up a PR which fixes this issue, but unfortunately it introduces a new one. The latest version of `yaml` changes the semantics for `undefined` to drop keys with undefined values rather than convert them to `null`. If this is an important feature to maintain, we'll likely need to hold off on this upgrade until the next version of `yaml` is released. They have already implemented options to fix this on the current `master` of that repo (see PR for full details).
