### ISSUE TITLE
[cdk8s] Getting ENOBUFS when including a larger than normal manifest file

### ISSUE THREAD

**Issue by van-vothanh** [awslabs/cdk8s#363]
Hello,

I'm running into an issue with my `cdk` and `cdk8s` (including `cdk8s+`) app when including a larger than normal manifest file.

Basically, what I'm trying to do is install the new `aws-load-balancer-controller` on my `EKS` cluster using `cdk8s`. As per this step (https://kubernetes-sigs.github.io/aws-load-balancer-controller/guide/controller/installation/#install-cert-manager) of the instructions, I need to install the `cert-manager` add-on, however as soon as I include its manifest file (https://github.com/jetstack/cert-manager/releases/download/v1.0.2/cert-manager.yaml), which is over 1.7MB, I receive an `ENOBUFS` error upon `cdk synth` or `cdk deploy`.

```typescript
new cdk8s.Include(this, `certificate-manager`, {
    url: 'https://github.com/jetstack/cert-manager/releases/download/v1.0.2/cert-manager.yaml'
});
```

Has anyone come across this issue and if so how did you guys get around it?

I did do a bit of digging and realised that the manifest file's size is a tad over the default nodejs's `child_process`'s `maxBuffer` of 1MB, and `cdk` currently doesn't give us the options to override this value (as per https://github.com/aws/aws-cdk/blob/5dcdecb2c5d6ce19517af66090cfacabed88025b/packages/aws-cdk/lib/api/cxapp/exec.ts#L106). Having said that, I'm not 100% sure if this is the culprit.

Thanks

**Comment by danikenan** [comment]
here is a solution. If allowed, will improve and make a pull request:

```
import { ApiObject, IncludeOptions } from 'cdk8s';
import { Construct, Node } from 'constructs';
import { resolve } from 'path';
import { existsSync, readFileSync, writeFileSync } from 'fs';
import request from 'sync-request';
import { safeLoadAll } from 'js-yaml';
import { tmpdir } from 'os';

export function load(url: string, cacheDir: string | false = tmpdir()) {
  const fileName = url.replace(/^.*\/([^/]+)$/, '$1');
  const cacheFileName = cacheDir ? resolve(cacheDir, fileName) : undefined;
  const yml =
    cacheFileName && existsSync(cacheFileName)
      ? readFileSync(cacheFileName, 'utf-8')
      : request('GET', url).getBody().toString('utf-8');
  if (cacheFileName && !existsSync(cacheFileName)) {
    writeFileSync(cacheFileName, yml);
  }
  const parts = safeLoadAll(yml);
  return parts;
}

export default class MyInclude extends Construct {
  constructor(scope: Construct, name: string, options: IncludeOptions) {
    super(scope, name);
    const objects = load(options.url);

    objects.forEach((obj, i) => {
      const name = obj.metadata?.name ?? `object${i++}`;
      // render an id: name[-kind][-namespace]
      const id = [name, obj.kind?.toLowerCase(), obj.metadata?.namespace].filter(x => x).join('-');
      new ApiObject(this, id, obj);
    });
  }

  public get apiObjects(): ApiObject[] {
    return Node.of(this).children.filter(o => o instanceof ApiObject) as ApiObject[];
  }
}
```

**Comment by iliapolo** [comment]
@danikenan Sorry the very delayed response. Thanks for the suggestion, but we try to avoid adding dependencies unless they are absolutely necessary.

This issue should now be resolved because we increased the buffer size to `10MB` in this [PR](https://github.com/awslabs/cdk8s/pull/454/files).
