### ISSUE TITLE
Java Getting Started uses wrong imports

### ISSUE THREAD

**Issue by anthonydahanne** [awslabs/cdk8s#406]
### Description of the bug:
The java getting started doc. references some non existent Kube* API.

### Reproduction Steps:

For example those [documented](https://github.com/awslabs/cdk8s/blob/master/docs/getting-started.md) imports: 

```
import imports.k8s.KubeService;
import imports.k8s.KubeServiceOptions;
```

don't resolve after doing a:
* `cdk8s init java-app`
* followed by a `cdk8s import `

### Other:

Also, there are some unused imports in the WebService example.

--- 

This is :bug: Bug Report

**Comment by iliapolo** [comment]
@anthonydahanne thanks for reporting this. Actually the latest version of the import does in fact have the `Kube` prefix. There are however other wrong and unused import which i've addressed [here](https://github.com/awslabs/cdk8s/pull/410/files).

Thanks.
