### ISSUE TITLE
cdk8s not getting updated with Homebrew

### ISSUE THREAD

**Issue by campionfellin** [awslabs/cdk8s#409]
### Description of the bug:

You can see the formulae version here:

https://github.com/Homebrew/homebrew-core/blob/da6d488a6c1cb1c35ac14c3f82e80d09228f62b6/Formula/cdk8s.rb

### Reproduction Steps:

```
brew install cdk8s
cdk8s --version
```

### Error Log:

In our release step:

```
Skipping: the formula version 'cdk8s-cli-0.33.0' is newer than 'cdk8s-cli-0.0.0'
```

(from: https://github.com/awslabs/cdk8s/runs/1427043718?check_suite_focus=true)

### Environment:

  - **Framework Version**:
  - **OS**:

### Other:

--- 

This is :bug: Bug Report

**Comment by campionfellin** [comment]
Reopening for discussion - @iliapolo the PR there should fix our bot so it opens up the PRs with Homebrew to update our Formula.

I was attempting to do it manually for the latest version [1.0.0-beta.3](https://www.npmjs.com/package/cdk8s-cli/v/1.0.0-beta.3) but that does not pass `brew audit --strict cdk8s` which fails with the error:

```
cdk8s:
  * Stable version URLs should not contain beta
```

Their docs [here](https://docs.brew.sh/Versions) say:

```
Unstable versions (alpha, beta, development versions) are not acceptable for versioned (or unversioned) formulae.
```

Can we release a stable 1.0.0 soon?

**Comment by iliapolo** [comment]
@campionfellin we are still not ready for a 1.0, and its going to probably be a little while.

Any chance you can do some more digging to see how beta versions are published to brew? do you think its just impossible?

**Comment by campionfellin** [comment]
Yes - certainly looks possible, [docs](https://docs.brew.sh/Formula-Cookbook#unstable-versions-devel-head)

If there's no plans to release 1.0 soon I'll try to publish the beta version

**Comment by campionfellin** [comment]
PR with Homebrew - https://github.com/Homebrew/homebrew-core/pull/65596

**Comment by campionfellin** [comment]
Going to mark this as blocked, until we get a stable `1.0.0` - in their [docs](https://docs.brew.sh/Versions):

```
Unstable versions (alpha, beta, development versions) are not acceptable for versioned (or unversioned) formulae.
```

And the PR was rejected.

**Comment by iliapolo** [comment]
@campionfellin I'm not sure I understand. I saw the rejection by homebrew, so is this comment still applicable? https://github.com/awslabs/cdk8s/issues/412#issuecomment-733019966

I can't understand if there is indeed a way to release the beta to brew or not :\

**Comment by campionfellin** [comment]
I am a bit confused myself on whether or not it is possible. In my PR with homebrew, it's pretty obvious that we're using a beta build:

```
head "https://registry.npmjs.org/cdk8s-cli/-/cdk8s-cli-1.0.0-beta.3.tgz"
```

I think if we change it to something like:

```
head "https://github.com/awslabs/cdk8s.git"
```

It might be acceptable. However, we can't change it to the Github link unless we publish the artifacts here.

**Comment by iliapolo** [comment]
Even if we did have the artifacts in GitHub it would still point to an obviously visible beta version indication.
If there isn't an official way to publish beta software to brew (which is silly because 0.x is also considered non stable) than we shouldn't be doing it.

Im ok with modifying the docs and just removing the brew installation method until we release 1.0, which a notice stating to the fact.

**Comment by eladb** [comment]
+1

**Comment by campionfellin** [comment]
Works for me! Closing.

**Comment by eladb** [comment]
Should we keep this open to track the work to update docs?
