### ISSUE TITLE
[cdk8s-cli] Github release of cli not working

### ISSUE THREAD

**Issue by campionfellin** [awslabs/cdk8s#412]
### Description of the bug:

https://github.com/awslabs/cdk8s/issues/409

Basically - to get `brew install cdk8s --head` to work (basically unstable/beta version) our Github releases need to be properly formatted.

Going here and downloading the zip file: https://github.com/awslabs/cdk8s/releases/tag/v1.0.0-beta.3

And extracting, you get a folder like:

```
├── packages
|  ├── cdk8s-cli
|  |  ├── bin
|  |  |  └── cdk8s
|  |  ├── src
|  |  |  ├── cli
```

(omitted non-relevant files).

That being said, the `cdk8s-cli` requires `lib`:

```
#!/usr/bin/env node
// eslint-disable-next-line @typescript-eslint/no-require-imports
require('../lib/cli');
```

### Reproduction Steps:

* Download ZIP of the release.
* Unzip it.
* Try to use the CLI with `bin/cdk8s --version`

### Error Log:

```
internal/modules/cjs/loader.js:1033
  throw err;
  ^

Error: Cannot find module '../lib/cli'
Require stack:
```

### Environment:

  - **Framework Version**:
  - **OS**:

### Other:

--- 

This is :bug: Bug Report

**Comment by campionfellin** [comment]
Seems like this is what's going on:

In our Release workflow, we upload an artifact:

https://github.com/awslabs/cdk8s/blob/ff5852c395d7b2044b1d3699e0b434f82e129333/.github/workflows/release.yml#L28-L32

But we don't use it for our Github releases:

https://github.com/awslabs/cdk8s/blob/ff5852c395d7b2044b1d3699e0b434f82e129333/.github/workflows/release.yml#L33-L36

Here is our `release-github.sh` script: https://github.com/awslabs/cdk8s/blob/master/tools/release-github.sh

---

Seems that we're not uploading compiled/built code, we're just zipping up the git repo... is that intended here?

**Comment by eladb** [comment]
We currently don't upload the build artifacts as part of the GitHub release because those artifacts are published to their respective package manager. 

Why can't brew download/install the CLI from npm? There should be a url that they can just hit to download the tarball.

**Comment by campionfellin** [comment]
Great callout, their documentation hinted at downloading from a `git` url, but seems that npm works just as well.

---

Are the Github releases then just snapshots of the repository? I think it makes sense to publish the artifacts with everything. Looks like it stopped publishing around v0.26.0.

**Comment by campionfellin** [comment]
Closing this, github release is working as intended.
