### ISSUE TITLE
cdk8s init failed on windows 10

### ISSUE THREAD

**Issue by diamondiona** [awslabs/cdk8s#414]
### Description of the bug:

cdk8s init python-app failed on windows 10. looks like it didn't find pipenv. but I can run pipenv successfully from command line

### Reproduction Steps:

cdk8s init python-app

### Error Log:

C:\work\cdk8s>cdk8s init python-app
Initializing a project from the python-app template
'which' is not recognized as an internal or external command,
operable program or batch file.
Unable to find "pipenv". Install from https://pipenv.kennethreitz.org

C:\work\cdk8s>pipenv --version
pipenv, version 2020.11.15

### Environment:

  - **Framework Version**: 1.0.0-beta.3
  - **OS**:windows 10

### Other:

--- 

This is :bug: Bug Report

**Comment by diamondiona** [comment]
looks like windows isn't an ideal platform. which OS supports best? should I use cloud9 IDE?

**Comment by iliapolo** [comment]
@diamondiona We try to support and fix bugs on all platforms. Please feel free to report any issue you discover on any platform.

**Comment by diamondiona** [comment]
I got the same error. Did I do something wrong? 

C:\Users\xg03789>npm install -g cdk8s-cli
C:\download\node-v12.18.3-win-x64\cdk8s -> C:\download\node-v12.18.3-win-x64\node_modules\cdk8s-cli\bin\cdk8s
+ cdk8s-cli@1.0.0-beta.3
updated 6 packages in 9.578s
C:\work\cdk8s>cdk8s init python-app
Initializing a project from the python-app template
'which' is not recognized as an internal or external command,
operable program or batch file.
Unable to find "pipenv". Install from https://pipenv.kennethreitz.org

**Comment by iliapolo** [comment]
@diamondiona Apologies, seems like there are a few issues with windows support, this being one of them. We will address them and try to release a fixed version soon. For now, any unix based OS should be ok.

I haven't tried Cloud9 myself but curious to hear about your experience if you decide to try it.

**Comment by sofferor** [comment]
On windows you need to install the CLI, run: "npm install -g cdk8s-cli"
