### ISSUE TITLE
cdk8s-plus-17 compile error

### ISSUE THREAD

**Issue by yjw113080** [awslabs/cdk8s#434]
### Description of the bug:

When I init cdk8s application and add cdk8s-plus-17 with `npm i cdk8s-plus-17`, I get typescript compile error.

### Reproduction Steps:

1. `cdk8s init typescript-app`
2. `npm i cdk8s-plus-17`
3. `npm run watch`

### Error Log:

node_modules/cdk8s-plus-17/lib/job.d.ts:1:50 - error TS2305: Module '"../../cdk8s/lib"' has no exported member 'Duration'.

1 import { ApiObject, ApiObjectMetadataDefinition, Duration } from 'cdk8s';
                                                   ~~~~~~~~

node_modules/cdk8s-plus-17/lib/probe.d.ts:1:10 - error TS2305: Module '"../../cdk8s/lib"' has no exported member 'Duration'.

1 import { Duration } from 'cdk8s';
           ~~~~~~~~

node_modules/cdk8s-plus-17/lib/volume.d.ts:1:10 - error TS2305: Module '"../../cdk8s/lib"' has no exported member 'Size'.

1 import { Size } from 'cdk8s';

### Environment:

  - **Framework Version**:
  "dependencies": {
    "cdk8s": "^0.27.0",
    "cdk8s-plus-17": "^1.0.0-beta.3",
    "constructs": "^2.0.2"
  }
  - **OS**: macOS Mojave 10.14.6(18G6042)

### Other:

--- 

This is :bug: Bug Report

**Comment by iliapolo** [comment]
@yjw113080 You need to use version `^1.0.0.-beta.3` of `cdk8s` as well, not just `cdk8s-plus-17`.
