### ISSUE TITLE
restrict CIDR IP addresses for a LoadBalancer type not supported

### ISSUE THREAD

**Issue by captainrandom** [awslabs/cdk8s#435]
### Description of the feature or enhancement:
I would like to restrict my service to whitelisted cdir IP ranges. This is already supported. See the `loadBalancerSourceRanges` on the following page:
https://aws.amazon.com/premiumsupport/knowledge-center/eks-cidr-ip-address-loadbalancer/

Right now there is no way to specify it using the current object configurations. Thus forcing me to use an escape hatch.

### Use Case:
Increase security by whitelisting certain IPs.

### Proposed Solution:
I'm not sure which object you should put this on, but I should be able to configure it on one of the "high level" apis  (cdk8s-plus or cdk8s-plus-17) without having to apply an escape hatch.

### Other:

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by iliapolo** [comment]
This should be added as a property on the [`Service`](https://github.com/awslabs/cdk8s/blob/master/packages/cdk8s-plus-17/src/service.ts#L10) construct. 👍
