### ISSUE TITLE
Vend the cdk8s-cli through standard package managers (homebrew etc)

### ISSUE THREAD

**Issue by eladb** [awslabs/cdk8s#49]
It is awkward to need to install node for non-JS languages. We should vend the CLI through homebrew and other popular package managers so their installation will be more idiomatic to each platform.

**Comment by eladb** [comment]
@campionfellin if you are interested to look into this, that would be helpful :-)

**Comment by campionfellin** [comment]
PR to `homebrew-core`: https://github.com/Homebrew/homebrew-core/pull/51851

**Comment by eladb** [comment]
Amazing! Would you like to update the getting started guides? (Under docs/)

**Comment by campionfellin** [comment]
Yes! PR has been merged with homebrew. Will update the getting started guides, and write a script to bump the brew version when we do releases.

**Comment by campionfellin** [comment]
Going to close this, as `cdk8s-cli` is available on both [npm](https://formulae.brew.sh/formula/cdk8s#default) and [brew](https://formulae.brew.sh/formula/cdk8s#default).

Please re-open if it should be available elsewhere (PyPi, etc)
