### ISSUE TITLE
Stop sorting the fields in alphabetical order in generated yaml file

### ISSUE THREAD

**Issue by Vinutha-Garimella** [awslabs/cdk8s#525]
### Description of the feature or enhancement:

Hi, I don't know whether this feature already exist or not, Can someone please help me with this issue.

When I run `cdk8s synth` yaml files are getting generated in dist folder. List or directory declared in .ts file is getting sorted alphabetically in generated yaml file, is there a way to not sort these fields..?

### Use Case: Avoiding alphabetical sort of dictionary or list resolves some pods to be not stuck in **Creating Container**
```
let tenant = new Tenant(this, 'tenant', {
            metadata: {
                name: 'minio',
                creationTimestamp: null,
                labels: {
                    app: 'minio'
                },
                scheduler: {
                    name: ""
                }
            },
            spec: {
                console: {
                    consoleSecret: {
                        name: 'minio-console-secret'
                    },
                    image: 'minio/console:v0.4.6',
                    replicas: 2,
                    resources: {},
                },
                credsSecret: {
                    name: 'minio-creds-secret'
                },
                image: 'minio/minio:RELEASE.2020-12-23T02-24-12Z',
                mountPath: '/export',
                requestAutoCert: true,
                zones: [
                    {
                        resources: {},
                        servers: 4,
                        volumeClaimTemplate: {
                            apiVersion: 'v1',
                            kind: 'persistentvolumeclaims',
                            spec: {
                                storageClassName: 'provisioner',
                                accessModes: ['ReadWriteOnce'],
                                resources: {
                                    requests: {
                                        storage: '1G'
                                    }
                                }
                            }
                        },
                        volumesPerServer: 1,
                        affinity: {
                            podAntiAffinity: {
                                preferredDuringSchedulingIgnoredDuringExecution: [
                                    {
                                        weight: 1,
                                        podAffinityTerm: {
                                            labelSelector: {
                                                matchExpressions: [
                                                    {
                                                        key: 'app',
                                                        operator: 'In',
                                                        values: ['minio']
                                                    }
                                                ]
                                            },
                                            topologyKey: 'kubernetes.io/hostname'
                                        }
                                    }
                                ]
                            }
                        }
                    }]
            }
        });
```

The generated yaml file from above .ts file is 
```apiVersion: "minio.min.io/v1"
kind: "Tenant"
metadata:
  labels:
    app: "minio"
  name: "minio"
  namespace: "minio"
  scheduler:
    name: ""
spec:
  console:
    consoleSecret:
      name: "minio-console-secret"
    image: "minio/console:v0.4.6"
    replicas: 2
    resources: {}
  credsSecret:
    name: "minio-creds-secret"
  image: "minio/minio:RELEASE.2020-12-23T02-24-12Z"
  mountPath: "/export"
  requestAutoCert: true
  zones:
    - affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: "app"
                      operator: "In"
                      values:
                        - "minio"
                topologyKey: "kubernetes.io/hostname"
              weight: 1
      resources: {}
      servers: 4
      volumeClaimTemplate:
        apiVersion: "v1"
        kind: "persistentvolumeclaims"
        spec:
          accessModes:
            - "ReadWriteOnce"
          resources:
            requests:
              storage: "1G"
          storageClassName: "provisioner"
      volumesPerServer: 
```
      
### Proposed Solution: Generate YAML file without alphabetical sort

```apiVersion: "minio.min.io/v1"
kind: "Tenant"
metadata:
  labels:
    app: "minio"
  name: "minio"
  namespace: "minio"
  scheduler:
    name: ""
spec:
  console:
    consoleSecret:
      name: "minio-console-secret"
    image: "minio/console:v0.4.6"
    replicas: 2
    resources: {}
  credsSecret:
    name: "minio-creds-secret"
  image: "minio/minio:RELEASE.2020-12-23T02-24-12Z"
  mountPath: "/export"
  requestAutoCert: true
  zones:
    - resources: {}
      servers: 4
      volumeClaimTemplate:
        apiVersion: "v1"
        kind: "persistentvolumeclaims"
        spec:
          accessModes:
            - "ReadWriteOnce"
          resources:
            requests:
              storage: "1G"
          storageClassName: "provisioner"
      volumesPerServer: 1
      affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: "app"
                  operator: In
                  values:
                  - minio
            topologyKey: "kubernetes.io/hostname"

**Comment by Vinutha-Garimella** [comment]
Hi, any update on this..?

**Comment by eladb** [comment]
I believe we are only sorting dictionaries which are expected to be unordered by definition. Can you expand on the use case for _not_ sorting dictionaries? Are you also seeing a sort of arrays?

**Comment by Vinutha-Garimella** [comment]
@eladb  as I mentioned earlier if the dictionaries get sorted during the cdk8s synth, the generated yaml fields are being evaluated first other than PVC's which is causing pods to be in `Container creating state`
```
kubectl get pods -n minio
NAME                              READY   STATUS              RESTARTS   AGE
minio-operator-6f5b8cdcff-85hsb   1/1     Running             0          148m
minio-zone-0-0                   0/1     ContainerCreating   0          127m
minio-zone-0-1                   0/1     ContainerCreating   0          127m
minio-zone-0-2                   0/1     ContainerCreating   0          127m
minio-zone-0-3                   0/1     ContainerCreating   0          127m
```

**Comment by eladb** [comment]
Trying to wrap my head around this - seems like you are defining a [MinIO Tenet](https://github.com/minio/operator/blob/master/docs/crd.adoc#k8s-api-github-com-minio-operator-pkg-apis-minio-min-io-v1-tenantspec), and I am curious if their documentation indicates that the order of the keys under `zones` is important. Do you have any reference for this or is it empirical?

**Comment by Vinutha-Garimella** [comment]
@eladb This issue is not only for minio tenant creation, I am facing this issue for elasticsearch, victoria metrics, mysql, postgres clusters. Basically if we have any configuration file with affinity prior to other configuration the pods are not getting created. I tried changing the order in the CRD's which were used for these cluster but no luck there I still get the yaml file in sorted order by causing issues with Pods

**Comment by Vinutha-Garimella** [comment]
Here is the yaml file that I used as reference while writing minio charts https://github.com/minio/operator/blob/master/examples/tenant.yaml

I had also created an issue with minio operator thinking that there is some issue with the minio CRD that I used
https://github.com/minio/operator/issues/451

**Comment by SpoortiPalakshaiah** [comment]
Hello @eladb, I'm also facing issues with sorted dictionary output; I'm trying to create Victoriametrics cluster yaml file using cdk8s typescript chart; And because of sort issue the pods are not coming up;

**Comment by Vinutha-Garimella** [comment]
Hi, any update on this..?

**Comment by eladb** [comment]
@SpoortiPalakshaiah can you share the YAML manifest that is failing and what exactly is not in the correct order?

**Comment by eladb** [comment]
CDK8s sorts keys to make sure the synthesized output is deterministic and stable, and the fundamental semantics of dictionaries is that they are unordered. Having said that, we understand reality can be a messy business, and we will consider adding a flag that will disable the use of [json-stable-stringify](https://github.com/substack/json-stable-stringify) to unblock such use cases.

BTW, it appears that the fields in the [MinIO CRD](https://github.com/minio/operator/blob/830b2dca738673156a559bdb7c9d8387522f062f/resources/base/crds/minio.min.io_tenants.yaml) are also sorted ([`affinity`] appears before [`volumeClaimTemplate`]). This makes me wonder if this is just  a MinIO bug. It is generally considered an anti-pattern to rely on the order of dictionary keys. Paging @nitisht from MinIO for visibility and perhaps some additional insight.

[`affinity`]: https://github.com/minio/operator/blob/830b2dca738673156a559bdb7c9d8387522f062f/resources/base/crds/minio.min.io_tenants.yaml#L521
[`volumeClaimTemplate`]: https://github.com/minio/operator/blob/830b2dca738673156a559bdb7c9d8387522f062f/resources/base/crds/minio.min.io_tenants.yaml#L2135

**Comment by eladb** [comment]
Stay tuned for https://github.com/awslabs/cdk8s/pull/534

**Comment by Vinutha-Garimella** [comment]
I did change the order of volumeClaimTemplate and affinity fields in MinIO CRD, to test the order in generated yaml file but affinity field was added before volumeClaimTemplate after executing `cdk8s synth`

[minio-minio.ts](https://github.com/awslabs/cdk8s/files/6005000/minio-minio.txt)

**Comment by Vinutha-Garimella** [comment]
Hi @eladb , I see that the code has been merged with a fix to disable the sort, where do  I set this `CDK8S_DISABLE_SORT=true` variable..?
should I export it as a environment variable before executing `cdk8s synth`..?

**Comment by eladb** [comment]
Either export it in your shell before you synth or set it in-process using something like:

```ts
process.env.CDK_DISABLE_SORT='true';
```

Before you create the `App` object.

Let me know if everything works as expected.

**Comment by Vinutha-Garimella** [comment]
@eladb thank you so much for you help, I am able to get generated yaml file in, unsorted way and pods are getting created now

**Comment by eladb** [comment]
Glad to hear! 🥇
