### ISSUE TITLE
[Suggestion] change —app to —cmd for cdk8s synth

### ISSUE THREAD

**Issue by CaerusKaru** [awslabs/cdk8s#56]
**Is your feature request related to a problem? Please describe.**
Since most people are creating cdk8s “apps”, it’s a little confusing that the “app” parameter for cdk8s synth takes in an executable and a file rather than the app name.

**Describe the solution you'd like**
We could change the parameter name to cmd to more clearly convey the intent: that this is the cmd used to run the synthesis.

**Describe alternatives you've considered**
We could leave it how it is since the templates make this pretty clear, but for those not using templates it’s still confusing. We could also just add better docs to the command line, but I don’t think this name is so important that it warrants keeping the name over adding docs.

**Comment by eladb** [comment]
I'd like this to be consistent with the AWS CDK, and we use `--app` there. One of the main reasons this is not "command" in the AWS CDK is that it can also accept a "cloud assembly" directory (the output of "cdk synth" which can then be used with `cdk deploy`.

Anyway, I am closing for now to avoid backlog, and we will reopen in case this becomes too confusing to people. In the AWS CDK that wasn't an issue.
