### ISSUE TITLE
Import Helm Charts

### ISSUE THREAD

**Issue by eladb** [awslabs/cdk8s#65]

**Comment by mbonig** [comment]
I recently went through the manual process of converting a helm chart (MySQL) to a cdk8s construct.  Not sure how you'd do it automatically unless there is a nice way of parsing go-templates...

**Comment by pgollucci** [comment]
how is this going to be different from cluster.addChart() ?

**Comment by manast** [comment]
no helm charts support is kind of no-go in current kubernetes deployment operations, it would be great if you could prioritize it up :).

**Comment by mbonig** [comment]
> no helm charts support is kind of no-go in current kubernetes deployment operations, it would be great if you could prioritize it up :).

Can you describe the use-case and how you imagine the solution might work?

**Comment by manast** [comment]
well most services that we would like to install are most conveniently installed using helm charts, cert-manager, redis, contour, etc.

**Comment by mbonig** [comment]
Importing helm charts, with all their templating, could be very difficult. Generally you'd likely have to rewrite any existing helm charts into constructs. I wrote up a guide when I did this for a MySQL helm chart to constructs, maybe it'll help:

https://www.openconstructfoundation.org/helm-to-cdk8s/

**Comment by eladb** [comment]
I was thinking to simply execute `helm template` during synth.

**Comment by manast** [comment]
@mbonig thats gonna be a no-go, maintaining constructs for every third-party helm chart we depend on is impracticable. 
Perhaps it is more difficult to implement helm charts supports in the CDK, but Pulumi seems to get this right: https://www.pulumi.com/docs/guides/adopting/from_kubernetes/

**Comment by mbonig** [comment]
> @mbonig thats gonna be a no-go, maintaining constructs for every third-party helm chart we depend on is impracticable.
> Perhaps it is more difficult to implement helm charts support in the CDK, but Pulumi seems to get this right: https://www.pulumi.com/docs/guides/adopting/from_kubernetes/

I'd love to dig into their code and see how they manage importing a helm chart.  It would be a powerful feature to have in the cdk8s.

**Comment by eladb** [comment]
> I'd love to dig into their code and see how they manage importing a helm chart. It would be a powerful feature to have in the cdk8s.

I expect this to be something like `helm template` under the hood

**Comment by mbonig** [comment]
I took a quick stab at this:

https://github.com/mbonig/helm-chart

Let me know what you think, @manast?

I purposely didn't look too much at what pulumi was doing, just tried to build something simple and easy to work with.

**Comment by manast** [comment]
Looks great. Will test it next week :).

**Comment by RichiCoder1** [comment]
Grafana's `tanka` just added an analogous feature: https://github.com/grafana/tanka/blob/master/CHANGELOG.md#wheel_of_dharma-helm-support

Also uses helm template, but has the addition of requiring you vendor the charts.

**Comment by mbonig** [comment]
> Grafana's `tanka` just added an analogous feature: https://github.com/grafana/tanka/blob/master/CHANGELOG.md#wheel_of_dharma-helm-support
> 
> Also uses helm template, but has the addition of requiring you vendor the charts.

I'm not familiar with tanka... could you offer a comparison between their method and the one I created (https://github.com/mbonig/helm-chart)?

**Comment by RichiCoder1** [comment]
Looking at it, two big differences:
1. Tanka requires the helm tool be installed, while yours appears to call into a docker image to template out the chart. 
2. Tanka has a feature that will download and manage local chart version for you, so you don't have to untar it yourself: https://tanka.dev/helm#vendoring-helm-charts

A minor difference is that the produced objects are named `${kind}_${metadata.name}`.

**Comment by mbonig** [comment]
> Looking at it, two big differences:
> 
> 1. Tanka requires the helm tool be installed, while yours appears to call into a docker image to template out the chart. (I actually prefer tanka's approach here, invoking docker for this seems a bit heavy)

I'm going to change this so it works similar to the NodejsFunction in the CDK, where it'll use docker if 'helm' isn't in the PATH or just execute helm directly if it is.

> 2. Tanka has a feature that will download and manage local "vendored" charts for you, so you don't have to untar them yourself: https://tanka.dev/helm#vendoring-helm-charts
> 
> A minor difference is that the produced objects are named `${kind}_${metadata.name}`.

I'll look into building similar functionality into it.

**Comment by mbonig** [comment]
Submitted a PR: https://github.com/awslabs/cdk8s/pull/346

**Comment by sunshineo** [comment]
@mbonig Great job. I found something maybe a bug and filed https://github.com/awslabs/cdk8s/issues/547
