### ISSUE TITLE
[BUG] release scripts run for forks

### ISSUE THREAD

**Issue by CaerusKaru** [awslabs/cdk8s#76]
**Describe the bug**
The release scripts currently run with commits to master on forked repositories, causing an error because the secrets are not available.

**To Reproduce**
Fork the repo, wait for an upstream commit to master and rebase, or commit directly to master.

**Expected behavior**
Release script should not run on forks

**Comment by eladb** [comment]
Thanks for reporting, I guess we will need to add some kind of condition on these workflows.

**Comment by campionfellin** [comment]
We could fix this by adding a check here:

https://github.com/awslabs/cdk8s/blob/9a02ea862b5337328acd171b70d73553fdec582a/.github/workflows/release.yml#L7-L10

for `if: github.repository == 'awslabs/cdk8s'`

This prevents the `build_artifact` job from running, and thus the rest as they all depend on it.

It's a bit hacky, but let me know if you can think of better alternatives.

**Comment by CaerusKaru** [comment]
I think the right answer is to check for the presence of the token in the environment. If it’s not set, it shouldn’t run.

**Comment by campionfellin** [comment]
Which token do you mean? Looks like the `secrets.GITHUB_TOKEN` is automatically created in your repository. 

https://help.github.com/en/actions/configuring-and-managing-workflows/authenticating-with-the-github_token

**Comment by CaerusKaru** [comment]
This is for the release script, so I would say the NPM token?

**Comment by campionfellin** [comment]
We have a handful of other tokens in the release script for Maven, Nuget, PyPi, and HomeBrew.

I think the solution here should be to check if it's the `awslabs/cdk8s` repository. What are your thoughts on this?

**Comment by CaerusKaru** [comment]
I realized that the lack of a token _should_ cause the workflow to fail; otherwise, we’d have no way of knowing if that was the case on master.

A repo name check seems fine to me, though it’s not the most ideal IMO (though I don’t presently have an alternative)
