### ISSUE TITLE
[Suggestion] allow to set the Python version for python-app

### ISSUE THREAD

**Issue by brennerm** [awslabs/cdk8s#91]
**Is your feature request related to a problem? Please describe.**
When initializing a new python-app cdk8s automatically sets the Python version for the pipenv to 3.7. As I'm running Ubuntu 18.04 which comes with Python 3.6 by default I end up with a lot of warnings but the execution of cdk8s works just fine.

**Describe the solution you'd like**
As I didn't encounter any problems running cdk8s with Python 3.6 I suppose it is compatible with Python versions lower than 3.7. If that's true it would be nice to be able to set the desired Python version when executing `cdk8s init python-app`. Something like `cdk8s init python-app --python-version 3.6` would be very nice.

**Comment by eladb** [comment]
Only python 3.7.7 and above is supported.
