### ISSUE TITLE
[Suggestion] allow cdk8s synth to print to stdout

### ISSUE THREAD

**Issue by brennerm** [awslabs/cdk8s#92]
**Is your feature request related to a problem? Please describe.**
Currently when using cdk8s with tools that can read K8s manifests from stdin I first need to execute `cdk8s synth` and afterwards `cat dist/*`.

**Describe the solution you'd like**
It would be nice to have the option to make `cdk8s synth` print directly to stdout. This could be achieved my some kind of flag, e.g. `cdk8s synth --print-to-stdout | kubectl apply -f`

**Comment by campionfellin** [comment]
@eladb I can do this. Do we expect this to be mutually exclusive with `--outdir`? Or would adding the flag `--print-to-stdout` be in addition to synthing to `dist`?

**Comment by eladb** [comment]
Mmmm. I am thinking probably mutually exclusive and perhaps we can change the name from `--outdir` to `--output` and then use the same switch for both.

**Comment by campionfellin** [comment]
Yeah I'm hesitant to changing the name so we don't introduce breaking changes. Will make it `--stdout`
