### ISSUE TITLE
[BUG] I should be able to import a CRD from an insecure server

### ISSUE THREAD

**Issue by campionfellin** [awslabs/cdk8s#94]
**Describe the bug**

I want to import my CRD from an `http` URL.

**To Reproduce**
Steps to reproduce the issue.

`cdk8s import http://example.com/myCRD.yml`

**Expected behavior**

I expect this to fetch from that server. I get a `Error: can't find file http://example.com/myCRD.yml` error)

**Additional context**

Fix is right around here:

https://github.com/awslabs/cdk8s/blob/edf2e8ce62a588b099be75a625b2323427d364d9/packages/cdk8s-cli/lib/import/crd.ts#L87-L97

---

This can be a good first issue for someone wanting to contribute! If no one picks it up for a while, I'll take it.

**Comment by cmdallas** [comment]
👋 I can pick this up.
